// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzGPrckeokpgmhT4QeM4fwMi40gMGYt_I',
    appId: '1:592999106220:web:aab499823a2fc32d950109',
    messagingSenderId: '592999106220',
    projectId: 'lostlink-536b9',
    authDomain: 'lostlink-536b9.firebaseapp.com',
    databaseURL: 'https://lostlink-536b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lostlink-536b9.firebasestorage.app',
    measurementId: 'G-YVCL88BG85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA09-vI78BP0anVSlootBSsBcMpGEhMo4w',
    appId: '1:592999106220:android:48f006570311fc60950109',
    messagingSenderId: '592999106220',
    projectId: 'lostlink-536b9',
    databaseURL: 'https://lostlink-536b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lostlink-536b9.firebasestorage.app',
  );
}
